### ISSUE TITLE
Using gitLastCommit with submodules fails

### ISSUE THREAD

**Issue by pcarr-m3** [foundeo/fixinator#14]
I can reproduce this by only updating the submodule (mrcore) in a pull request and letting Jenkins run the pipeline.  Below is the command parameters being used as well as the console output.

```
+ /usr/local/bin/box fixinator path=. gitLastCommit=true resultFormat=junit resultFile=./fixinator-report.xml
fixinator v3.0.2 built by Foundeo Inc.

    ___                      _             
   / __)                    | |            
 _| |__ ___  _   _ ____   __| |_____  ___  
(_   __) _ \| | | |  _ \ / _  | ___ |/ _ \ 
  | | | |_| | |_| | | | ( (_| | ____| |_| |
  |_|  \___/|____/|_| |_|\____|_____)\___/ 
                                         inc.


Fixinator will send source code to: https://api.fixinator.app/v1/scan
for scanning. The code is kept in RAM during scanning and is not persisted.
For details see: https://github.com/foundeo/fixinator/wiki/How-Does-Fixinator-Work

Note: The enterprise version allows you to run the code scanner fully on your own servers.
Detected CI Environment, I will continue without prompting
Fixinator API Server: https://api.fixinator.app/v1/scan
Scanning only files changed in the last git commit.
  M: v2/mrcore

Scanning /opt/jenkins/workspace/PR-155/




[38;5;15m[48;5;9mERROR (5.6.1+00618)[0m

[38;5;9m[1mMissing categories data, make sure you are using the latest fixinator server version.[0m

[38;5;9m[1m[0m
[38;5;6m[1m/modules/fixinator/models/fixinator/FixinatorReport.cfc: line 293
[0m291: 			</cfloop>
292: 		<cfelse>
[1m293: 			<cfthrow message="Missing categories data, make sure you are using the latest fixinator server version.">[0m
294: 		</cfif>
295: 		<!--- ensure that nothing was missed due to missing category data --->
[38;5;6m[1mcalled from [0m[38;5;6m[1m/modules/fixinator/models/fixinator/FixinatorReport.cfc: line 31
[0m[38;5;6m[1mcalled from [0m[38;5;6m[1m/modules/fixinator/commands/fixinator.cfc: line 416
[0m[38;5;6m[1mcalled from [0m[38;5;6m[1m/system/services/CommandService.cfc: line 443
[0m[38;5;6m[1mcalled from [0m[38;5;6m[1m/system/services/CommandService.cfc: line 245
[0m[38;5;6m[1mcalled from [0m[38;5;6m[1m/system/Shell.cfc: line 817
[0m[38;5;6m[1mcalled from [0m[38;5;6m[1m/system/Bootstrap.cfm: line 119
[0m
[38;5;15mTo enable full stack trace, run [0m[38;5;11m[1mconfig set verboseErrors=true[0m

Post stage
[Pipeline] junit
Recording test results
No test report files were found. Configuration error?
Error when executing always post condition:
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to buildhost
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1000)
		at hudson.FilePath.act(FilePath.java:1186)
		at hudson.FilePath.act(FilePath.java:1175)
		at hudson.tasks.junit.JUnitParser.parseResult(JUnitParser.java:118)
		at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:157)
		at hudson.tasks.junit.JUnitResultArchiver.parseAndSummarize(JUnitResultArchiver.java:251)
		at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:63)
		at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:29)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
hudson.AbortException: No test report files were found. Configuration error?
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:184)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3492)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:377)
	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by pfreitag** [comment]
Thanks for the report Peter, I will look into this and get back to you.

**Comment by pfreitag** [comment]
I think this error was due to the fixinator enterprise server being out of date, updating the fixinator enterprise server version should fix this. Let me know if you are still having the issue and I can take another look.
